# Define ports to expose and actions on serve
ports:
  - port: 3000
    onOpen: open-preview

# Start-up tasks: downloading HyperExecute, configuring, and running tasks
tasks:
  - name: Setup and Configure HyperExecute
    before: |
      # Download HyperExecute CLI for Windows
      curl -s -o hyperexecute.exe https://downloads.lambdatest.com/hyperexecute/windows/hyperexecute.exe
      chmod +x hyperexecute.exe
      
      # Verify the binary is properly set
      echo "HyperExecute CLI downloaded and configured for Windows"

    init: |
      # Run HyperExecute task with appropriate credentials and YAML config
      if "%LT_USERNAME%" == "" (
        echo "Error: LT_USERNAME environment variable is not set."
        exit /b 1
      )
      if "%LT_ACCESS_KEY%" == "" (
        echo "Error: LT_ACCESS_KEY environment variable is not set."
        exit /b 1
      )

      echo "Starting HyperExecute task on Windows..."
      hyperexecute.exe --user="%LT_USERNAME%" --key="%LT_ACCESS_KEY%" ^
                       --config win11/.hyperexecute_autosplits.yaml ^
                       --download-artifacts ^
                       --force-clean-artifacts
      echo "HyperExecute task completed successfully!"

  - name: Post-Test Cleanup (Optional)
    command: |
      # Optional: Clean up artifacts or perform additional steps
      echo "Post-test cleanup completed."
